// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL9sCrhiqFRRu1jwUC2UddNAGEFrQOxUg',
    appId: '1:185361996865:web:7464473a5600bc69b33ac0',
    messagingSenderId: '185361996865',
    projectId: 'coffee-shop-13226',
    authDomain: 'coffee-shop-13226.firebaseapp.com',
    databaseURL: 'https://coffee-shop-13226-default-rtdb.firebaseio.com',
    storageBucket: 'coffee-shop-13226.firebasestorage.app',
    measurementId: 'G-Z4H95M2SXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Upji0D1pLAXQy-3Re1gklwWr0IiGyN8',
    appId: '1:185361996865:android:1c5215e8ac24d325b33ac0',
    messagingSenderId: '185361996865',
    projectId: 'coffee-shop-13226',
    databaseURL: 'https://coffee-shop-13226-default-rtdb.firebaseio.com',
    storageBucket: 'coffee-shop-13226.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBweo825aov_XeMGtlutekxRV1ef2GECWw',
    appId: '1:185361996865:ios:72a358a108bf3ac5b33ac0',
    messagingSenderId: '185361996865',
    projectId: 'coffee-shop-13226',
    databaseURL: 'https://coffee-shop-13226-default-rtdb.firebaseio.com',
    storageBucket: 'coffee-shop-13226.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBweo825aov_XeMGtlutekxRV1ef2GECWw',
    appId: '1:185361996865:ios:72a358a108bf3ac5b33ac0',
    messagingSenderId: '185361996865',
    projectId: 'coffee-shop-13226',
    databaseURL: 'https://coffee-shop-13226-default-rtdb.firebaseio.com',
    storageBucket: 'coffee-shop-13226.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL9sCrhiqFRRu1jwUC2UddNAGEFrQOxUg',
    appId: '1:185361996865:web:59936462ab8c8dd8b33ac0',
    messagingSenderId: '185361996865',
    projectId: 'coffee-shop-13226',
    authDomain: 'coffee-shop-13226.firebaseapp.com',
    databaseURL: 'https://coffee-shop-13226-default-rtdb.firebaseio.com',
    storageBucket: 'coffee-shop-13226.firebasestorage.app',
    measurementId: 'G-P2VRTPNXN3',
  );
}
